Update action.yaml for inspector

diff --git a/scan_image/action.yaml b/scan_image/action.yaml
--- a/scan_image/action.yaml
+++ b/scan_image/action.yaml
@@ -18,33 +18,25 @@ runs:
         echo "AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)" >> $GITHUB_ENV
         echo "AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)" >> $GITHUB_ENV
 
-    - name: Inspector Scan
-      id: inspector
-      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.0.0
-      with:
-        artifact_type: 'container'
-        artifact_path: ${{ inputs.tar_file }}
-        display_vulnerability_findings: "enabled"
-        critical_threshold: 0
+name: Inspector Scan
+        uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.0.0
+        with:
+          artifact_type: 'container'
+          artifact_path: ${{ inputs.image }}
+          display_vulnerability_findings: "enabled"
+          critical_threshold: 0
 
-    - name: Display CycloneDX SBOM (JSON)
-      shell: bash
-      run: cat ${{ steps.inspector.outputs.artifact_sbom }}
+      - name: Display Inspector vulnerability scan results (JSON)
+        run: cat ${{ steps.inspector.outputs.inspector_scan_results }}
 
-    - name: Display Inspector vulnerability scan results (JSON)
-      shell: bash
-      run: cat ${{ steps.inspector.outputs.inspector_scan_results }}
+      - name: Display Inspector vulnerability scan results (Markdown)
+        run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}
 
-    - name: Display Inspector vulnerability scan results (Markdown)
-      shell: bash
-      run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}
-
-    - name: On vulnerability threshold exceeded
-      shell: bash
-      run: |
-        if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
-          echo "Vulnerability threshold exceeded. Failing the job."
-          exit 1
-        else
-          echo "Vulnerability threshold not exceeded. Continuing."
-        fi
+      - name: On vulnerability threshold exceeded
+        run: |
+          if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
+            echo "Vulnerability threshold exceeded. Failing the job."
+            exit 1
+          else
+            echo "Vulnerability threshold not exceeded. Continuing."
+          fi
