Update action.yaml

diff --git a/scan_image/action.yaml b/scan_image/action.yaml
--- a/scan_image/action.yaml
+++ b/scan_image/action.yaml
@@ -17,6 +17,7 @@ runs:
         echo "AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' creds.json)" >> $GITHUB_ENV
         echo "AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' creds.json)" >> $GITHUB_ENV
         echo "AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' creds.json)" >> $GITHUB_ENV
+
     - name: Inspector Scan
       id: inspector
       uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.0.0
@@ -26,17 +27,17 @@ runs:
           display_vulnerability_findings: "enabled"
           critical_threshold: 0
 
-      - name: Display Inspector vulnerability scan results (JSON)
-        run: cat ${{ steps.inspector.outputs.inspector_scan_results }}
+    - name: Display Inspector vulnerability scan results (JSON)
+      run: cat ${{ steps.inspector.outputs.inspector_scan_results }}
 
-      - name: Display Inspector vulnerability scan results (Markdown)
-        run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}
+    - name: Display Inspector vulnerability scan results (Markdown)
+      run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}
 
-      - name: On vulnerability threshold exceeded
-        run: |
-          if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
-            echo "Vulnerability threshold exceeded. Failing the job."
-            exit 1
-          else
-            echo "Vulnerability threshold not exceeded. Continuing."
-          fi
+    - name: On vulnerability threshold exceeded
+      run: |
+        if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
+          echo "Vulnerability threshold exceeded. Failing the job."
+          exit 1
+        else
+          echo "Vulnerability threshold not exceeded. Continuing."
+        fi
